application: mb-expense-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static/expenses
  static_dir: expenses/static/expenses
  expiration: '0'





